#ifndef _DBG_INTERACTION_STD_IDS_H_
#define _DBG_INTERACTION_STD_IDS_H_

typedef enum {
	DBG_CMD_STD_ID_PARSE_ERROR = 0,
	DBG_CMD_STD_ID_BREAK,
	DBG_CMD_STD_ID_DELETE,
	DBG_CMD_STD_ID_CONT,
	DBG_CMD_STD_ID_INTR,
	DBG_CMD_STD_ID_DATA_WATCH,
	DBG_CMD_STD_ID_ELAPS,
	DBG_CMD_STD_ID_NEXT,
	DBG_CMD_STD_ID_RETURN,
	DBG_CMD_STD_ID_VIEW,
	DBG_CMD_STD_ID_PRINT,
	DBG_CMD_STD_ID_MEMSET,
	DBG_CMD_STD_ID_QUIT,
	DBG_CMD_STD_ID_EXIT,
	DBG_CMD_STD_ID_SERIALIN,
	DBG_CMD_STD_ID_INFO_CPU,
	DBG_CMD_STD_ID_FUNC_TRACE,
	DBG_CMD_STD_ID_DATA_ACCESS_INFO,
	DBG_CMD_STD_ID_BACK_TRACE,
	DBG_CMD_STD_ID_PROFILE,
	DBG_CMD_STD_ID_LIST,
	DBG_CMD_STD_ID_HELP,
	DBG_CMD_STD_ID_TARGET
} DbgCmdStdIdType;

#define DBG_CMD_STD_ID_NUM	(DBG_CMD_STD_ID_TARGET - 1) //DBG_CMD_STD_ID_PARSE_ERRORは含まない．

#endif /* _DBG_INTERACTION_STD_IDS_H_ */
