ROOT_PATH 		:= ..
ATHRILL_ROOT	:= $(ROOT_PATH)/../../trunk/src
BUILD_PATH		:= $(ROOT_PATH)/build/v850esfk3
CPU_CONFIG_PATH	:= $(ATHRILL_ROOT)/config/target/v850esfk3


include $(BUILD_PATH)/Makefile.common
